// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Dummy.EF.Entidade;

namespace Dummy.EF.Dado
{
    public partial class BeneflexSanofiContext : DbContext
    {
        public BeneflexSanofiContext()
        {
        }

        public BeneflexSanofiContext(DbContextOptions<BeneflexSanofiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AlteracaoUsuario> AlteracaoUsuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AlteracaoUsuario>(entity =>
            {
                entity.HasKey(e => e.IdAlteracaoUsuario)
                    .HasName("PK__Alteraca__221B978D451ED118");

                entity.ToTable("AlteracaoUsuario", "historico");

                entity.Property(e => e.Acao)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Celular)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Cpf)
                    .IsRequired()
                    .HasColumnName("CPF")
                    .HasMaxLength(11)
                    .IsUnicode(false);

                entity.Property(e => e.DataAlteracao).HasColumnType("datetime");

                entity.Property(e => e.DataNascimento).HasColumnType("date");

                entity.Property(e => e.EmailContato)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.EmailMicrosoft)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.NomeMae)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.NomeSocial)
                    .IsRequired()
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.OrgaoEmissor)
                    .HasMaxLength(6)
                    .IsUnicode(false);

                entity.Property(e => e.Rg)
                    .HasColumnName("RG")
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.Sexo)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Telefone)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}