// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Dummy.EF.Entidade
{
    public partial class AlteracaoUsuario
    {
        public int IdAlteracaoUsuario { get; set; }
        public int IdUsuario { get; set; }
        public string Acao { get; set; }
        public DateTime DataAlteracao { get; set; }
        public string EmailContato { get; set; }
        public string Nome { get; set; }
        public string NomeSocial { get; set; }
        public string Cpf { get; set; }
        public string Rg { get; set; }
        public string Sexo { get; set; }
        public DateTime DataNascimento { get; set; }
        public string NomeMae { get; set; }
        public int IdStatus { get; set; }
        public string EmailMicrosoft { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string OrgaoEmissor { get; set; }
        public int IdParametrizacao { get; set; }
    }
}