// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Dummy.Models
{
    public partial class SANOFI_BNFContext : DbContext
    {
        public SANOFI_BNFContext()
        {
        }

        public SANOFI_BNFContext(DbContextOptions<SANOFI_BNFContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DataEfetiva> DataEfetiva { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DataEfetiva>(entity =>
            {
                entity.HasKey(e => e.IdDataEfetiva)
                    .HasName("PK__DataEfet__55D3DD5BB4AE1A7A");

                entity.ToTable("DataEfetiva", "processo");

                entity.Property(e => e.DataCriacao).HasColumnType("datetime");

                entity.Property(e => e.DataEfetiva1)
                    .HasColumnName("DataEfetiva")
                    .HasColumnType("datetime");

                entity.Property(e => e.Valor)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}